# Generated by Django 5.0 on 2023-12-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcd_render', '0003_rename_nome_completo_form_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormModel',
        ),
    ]
