# Generated by Django 5.0 on 2023-12-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd_render', '0004_rename_form_formmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
    ]
