# Generated by Django 5.0 on 2023-12-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd_render', '0005_formmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
